server:
  port: 8888

spring:
  datasource:
    druid:
      #   数据源基本配置
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mystudy?characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT%2B8&allowMultiQueries=true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  task: false
  rabbitmq:
    host: 192.168.130.128
    port: 5672
    username: guest
    password: guest
    queue: test
    publisher-confirm: correlated
    publisher-returns: true
    virtual-host: /

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.weis.dao: debug

